# Generated by Django 2.1.5 on 2019-02-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_course_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyMaterial',
            new_name='StudyMaterials',
        ),
    ]
