# Generated by Django 2.1.5 on 2019-02-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_auto_20190219_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='language_course',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_course', to='cmsapp.LanguageCourse'),
        ),
    ]
